SELECT
    b.O_ORDERKEY AS ORDER_ID,
    b.O_CUSTKEY AS CUSTOMER_ID,
    b.O_ORDERDATE AS ORDER_DATE,
    DATE_ADD(b.O_ORDERDATE, INTERVAL 20 DAY) AS TRANSACTION_DATE,
    FARM_FINGERPRINT(RPAD(CONCAT(CAST(b.O_ORDERKEY AS STRING), CAST(b.O_CUSTKEY AS STRING), FORMAT_DATE('%Y%m%d', b.O_ORDERDATE)), 24, '0')) AS TRANSACTION_NUMBER,
    b.O_TOTALPRICE AS AMOUNT,
    CAST(
    CASE CAST(FLOOR(RAND() * 2) AS INT64) + 1
        WHEN 1 THEN 'DR'
        WHEN 2 THEN 'CR'
    END AS STRING) AS TYPE
FROM {{ source('snowflake_dummy_data', 'ORDERS') }}  AS b
LEFT JOIN {{ source('snowflake_dummy_data', 'CUSTOMER') }} AS c
    ON b.O_CUSTKEY = c.C_CUSTKEY
WHERE b.O_ORDERDATE = CAST('{{ var('load_date') }}' AS DATE)