version: 2

sources:
  - name: snowflake_dummy_data
    database: "{{ env_var('LZ_PROJECT_ID', 'internal-data-lz-dev-7c5c') }}"
    schema: "{{ var('snowflake_dummy_data_dataset') }}"
    tables:
      - name: LINEITEM
      - name: CUSTOMER
      - name: ORDERS
      - name: PARTSUPP
      - name: SUPPLIER
      - name: PART
      - name: NATION
      - name: REGION
