version: 2

sources:
  - name: snowflake_dummy_data
    database: "{{ var('landing_zone_project') }}"
    schema: "{{ var('snowflake_dummy_data_dataset') }}"
    tables:
      - name: LINEITEM
      - name: CUSTOMER
      - name: ORDERS
      - name: PARTSUPP
      - name: SUPPLIER
      - name: PART
      - name: NATION
      - name: REGION
